/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abcweddinghallbooking_ms.View;

import abcweddinghallbooking_ms.Controller.BookingDAOImp;
import abcweddinghallbooking_ms.Controller.HallDAOImp;
import abcweddinghallbooking_ms.Model.Booking;
import java.awt.geom.RoundRectangle2D;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanduni punchihewa
 */
public class ACancellation extends javax.swing.JFrame {

    /**
     * Creates new form ACancellation
     */
    public ACancellation() {
        initComponents();
        Load();
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),40,40));
        curDateTime();
    }
    
    
    public void curDateTime(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd    HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        lblDate.setText(dtf.format(now));
    }
     public void Load() {
        BookingDAOImp dao = new BookingDAOImp();
        List<Booking> list = dao.list();
        DefaultTableModel dft = (DefaultTableModel) tblBooking.getModel();
        dft.setRowCount(0);
        for (Booking book : list) {
            int bookid = book.getBooking_id();
            int customerid = book.getCustomer_id();
            int hallid = book.getHall_id();
            int priceperday = book.getPrice_per_day();
            Date checkin = book.getCheck_in();
            Date checkOut = book.getCheck_out();
            int totalAmount = book.getTotal_amount();
            String paymentType = book.getPayment_type();
            String payment = book.getPayment();
            

            dft.addRow(new Object[]{bookid, customerid, hallid, priceperday, checkin, checkOut, totalAmount, paymentType, payment});
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        rSButtonHover1 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover11 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover10 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover9 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover8 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover6 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover5 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover4 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover3 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover2 = new rojeru_san.complementos.RSButtonHover();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCustomerID = new rojerusan.RSMetroTextPlaceHolder();
        txtHallID = new rojerusan.RSMetroTextPlaceHolder();
        txtPayment = new rojerusan.RSMetroTextPlaceHolder();
        btnLogin = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooking = new rojeru_san.complementos.RSTableMetro();
        jLabel18 = new javax.swing.JLabel();
        btnDelete = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel5.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel5.setkStartColor(new java.awt.Color(51, 102, 0));
        kGradientPanel5.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ABC COMPANY - RESOURCE ALLOCATION SYSTEM");
        jLabel4.setAlignmentY(0.0F);
        kGradientPanel5.add(jLabel4);
        jLabel4.setBounds(266, 12, 491, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/luxury.png"))); // NOI18N
        kGradientPanel5.add(jLabel2);
        jLabel2.setBounds(230, 12, 24, 24);

        jPanel3.setBackground(new java.awt.Color(204, 51, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(2, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        kGradientPanel5.add(jPanel3);
        jPanel3.setBounds(48, 12, 4, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menu (1).png"))); // NOI18N
        kGradientPanel5.add(jLabel1);
        jLabel1.setBounds(12, 12, 24, 24);

        lblDate.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("2022.05.04   23:34:45");
        kGradientPanel5.add(lblDate);
        lblDate.setBounds(810, 20, 200, 14);

        getContentPane().add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 50));

        kGradientPanel6.setkEndColor(new java.awt.Color(0, 204, 51));
        kGradientPanel6.setkStartColor(new java.awt.Color(0, 51, 0));
        kGradientPanel6.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel4);
        jPanel4.setBounds(0, 0, 50, 40);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel5);
        jPanel5.setBounds(0, 50, 50, 40);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/municipal.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel6);
        jPanel6.setBounds(0, 100, 50, 40);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel7);
        jPanel7.setBounds(0, 150, 50, 40);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel8);
        jPanel8.setBounds(0, 200, 50, 40);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/click.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel9);
        jPanel9.setBounds(0, 250, 50, 40);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/document.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel10);
        jPanel10.setBounds(0, 300, 50, 40);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/online-payment.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel11);
        jPanel11.setBounds(0, 350, 50, 40);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel12);
        jPanel12.setBounds(0, 530, 50, 40);

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/no.png"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel13);
        jPanel13.setBounds(0, 580, 50, 40);

        rSButtonHover1.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover1.setText("Exit");
        rSButtonHover1.setColorHover(java.awt.Color.red);
        rSButtonHover1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover1);
        rSButtonHover1.setBounds(50, 580, 180, 40);

        rSButtonHover11.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover11.setText("LogOut");
        rSButtonHover11.setColorHover(java.awt.Color.orange);
        rSButtonHover11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover11ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover11);
        rSButtonHover11.setBounds(50, 530, 180, 40);

        rSButtonHover10.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover10.setText("Payment");
        rSButtonHover10.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover10.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover10ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover10);
        rSButtonHover10.setBounds(50, 350, 180, 40);

        rSButtonHover9.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonHover9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(51, 255, 0)));
        rSButtonHover9.setText("Cancellation");
        rSButtonHover9.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonHover9.setColorText(new java.awt.Color(0, 51, 0));
        rSButtonHover9.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover9ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover9);
        rSButtonHover9.setBounds(50, 300, 180, 40);

        rSButtonHover8.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover8.setText("Booking");
        rSButtonHover8.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover8.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover8ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover8);
        rSButtonHover8.setBounds(50, 250, 180, 40);

        rSButtonHover6.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover6.setText("Customer");
        rSButtonHover6.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover6.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover6ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover6);
        rSButtonHover6.setBounds(50, 200, 180, 40);

        rSButtonHover5.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover5.setText("Search Hall");
        rSButtonHover5.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover5.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover5ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover5);
        rSButtonHover5.setBounds(50, 150, 180, 40);

        rSButtonHover4.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover4.setText("Hall");
        rSButtonHover4.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover4.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover4ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover4);
        rSButtonHover4.setBounds(50, 100, 180, 40);

        rSButtonHover3.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover3.setText("Admin");
        rSButtonHover3.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover3.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover3ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover3);
        rSButtonHover3.setBounds(50, 50, 180, 40);

        rSButtonHover2.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover2.setText("Home");
        rSButtonHover2.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover2.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover2ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover2);
        rSButtonHover2.setBounds(50, 0, 190, 40);

        getContentPane().add(kGradientPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 230, 630));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 0));
        jLabel15.setText("ID No :");
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        txtID.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtID.setForeground(new java.awt.Color(0, 51, 0));
        txtID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 0)));
        jPanel14.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 148, 26));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 0));
        jLabel16.setText("Customer ID:");
        jPanel14.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 0));
        jLabel17.setText("Hall ID :");
        jPanel14.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        txtCustomerID.setBackground(new java.awt.Color(204, 255, 255));
        txtCustomerID.setForeground(new java.awt.Color(0, 51, 0));
        txtCustomerID.setBorderColor(new java.awt.Color(204, 0, 0));
        txtCustomerID.setBotonColor(new java.awt.Color(0, 51, 0));
        txtCustomerID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerID.setPhColor(new java.awt.Color(0, 51, 51));
        txtCustomerID.setPlaceholder("Customer ID");
        txtCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIDActionPerformed(evt);
            }
        });
        jPanel14.add(txtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 140, -1));

        txtHallID.setBackground(new java.awt.Color(204, 255, 255));
        txtHallID.setForeground(new java.awt.Color(0, 51, 0));
        txtHallID.setBorderColor(new java.awt.Color(204, 0, 0));
        txtHallID.setBotonColor(new java.awt.Color(0, 51, 0));
        txtHallID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHallID.setPhColor(new java.awt.Color(0, 51, 51));
        txtHallID.setPlaceholder("Hall ID");
        jPanel14.add(txtHallID, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 140, -1));

        txtPayment.setBackground(new java.awt.Color(204, 255, 255));
        txtPayment.setForeground(new java.awt.Color(0, 51, 0));
        txtPayment.setBorderColor(new java.awt.Color(204, 0, 0));
        txtPayment.setBotonColor(new java.awt.Color(0, 51, 0));
        txtPayment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPayment.setPhColor(new java.awt.Color(0, 51, 51));
        txtPayment.setPlaceholder("Payment Status");
        txtPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentActionPerformed(evt);
            }
        });
        jPanel14.add(txtPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 140, -1));

        btnLogin.setBackground(new java.awt.Color(0, 102, 0));
        btnLogin.setText("Search");
        btnLogin.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel14.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 121, 47));

        tblBooking.setBackground(new java.awt.Color(0, 51, 0));
        tblBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Customer ID", "Hall ID", "Price per Day", "Check In", "Check Out", "Total Amount", "Payment Type", "Payment"
            }
        ));
        tblBooking.setColorBackgoundHead(new java.awt.Color(0, 51, 0));
        tblBooking.setColorFilasForeground1(new java.awt.Color(0, 102, 0));
        tblBooking.setColorFilasForeground2(new java.awt.Color(0, 102, 0));
        tblBooking.setColorSelBackgound(new java.awt.Color(0, 102, 0));
        tblBooking.setFuenteFilas(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblBooking.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblBooking.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBooking);

        jPanel14.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 766, 280));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 0));
        jLabel18.setText("Payment Status :");
        jPanel14.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));

        btnDelete.setBackground(new java.awt.Color(0, 51, 51));
        btnDelete.setText("Delete Booking");
        btnDelete.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel14.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 190, 47));

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 790, 630));

        setSize(new java.awt.Dimension(1018, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void rSButtonHover11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover11ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover11ActionPerformed

    private void rSButtonHover10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover10ActionPerformed
        Apayment payment = new Apayment();
        payment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover10ActionPerformed

    private void rSButtonHover9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover9ActionPerformed
        ACancellation cancellation = new ACancellation();
        cancellation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover9ActionPerformed

    private void rSButtonHover8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover8ActionPerformed
        ABookingHall booking = new ABookingHall();
        booking.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover8ActionPerformed

    private void rSButtonHover6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover6ActionPerformed
        ACustomer customer = new ACustomer();
        customer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover6ActionPerformed

    private void rSButtonHover5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover5ActionPerformed
        AsearchHall asearch = new AsearchHall();
        asearch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover5ActionPerformed

    private void rSButtonHover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover4ActionPerformed
        AHall ahall = new AHall();
        ahall.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover4ActionPerformed

    private void rSButtonHover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover3ActionPerformed
        User user = new User();
        user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover3ActionPerformed

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed
        AdminHome ahome = new AdminHome();
        ahome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
         int id = Integer.parseInt(txtID.getText());

    BookingDAOImp dao = new BookingDAOImp();
    Booking book = dao.get(id);
    

    txtCustomerID.setText(String.valueOf(book.getCustomer_id()));
    txtHallID.setText(String.valueOf(book.getHall_id()));
    txtPayment.setText(book.getPayment());
       
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerIDActionPerformed

    private void txtPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       Booking book = new Booking();

        int id = Integer.parseInt(txtID.getText());

        book.setBooking_id(id);

        BookingDAOImp dao = new BookingDAOImp();
        dao.delete(book);
        
        
        // Update the availability column in the hall table to "available"
    int hallID = Integer.parseInt(txtHallID.getText());
    HallDAOImp hallDAO = new HallDAOImp();
    hallDAO.updateAvailability(hallID, "Available");
        
        
        
        
        Load();
        txtCustomerID.setText("");
        txtHallID.setText("");
        txtID.setText("");
        txtPayment.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookingMouseClicked
        
    }//GEN-LAST:event_tblBookingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ACancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ACancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ACancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ACancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ACancellation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnDelete;
    private rojerusan.RSMaterialButtonRectangle btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private javax.swing.JLabel lblDate;
    private rojeru_san.complementos.RSButtonHover rSButtonHover1;
    private rojeru_san.complementos.RSButtonHover rSButtonHover10;
    private rojeru_san.complementos.RSButtonHover rSButtonHover11;
    private rojeru_san.complementos.RSButtonHover rSButtonHover2;
    private rojeru_san.complementos.RSButtonHover rSButtonHover3;
    private rojeru_san.complementos.RSButtonHover rSButtonHover4;
    private rojeru_san.complementos.RSButtonHover rSButtonHover5;
    private rojeru_san.complementos.RSButtonHover rSButtonHover6;
    private rojeru_san.complementos.RSButtonHover rSButtonHover8;
    private rojeru_san.complementos.RSButtonHover rSButtonHover9;
    private rojeru_san.complementos.RSTableMetro tblBooking;
    private rojerusan.RSMetroTextPlaceHolder txtCustomerID;
    private rojerusan.RSMetroTextPlaceHolder txtHallID;
    private javax.swing.JTextField txtID;
    private rojerusan.RSMetroTextPlaceHolder txtPayment;
    // End of variables declaration//GEN-END:variables
}
