/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abcweddinghallbooking_ms.View;

import abcweddinghallbooking_ms.Controller.CustomerDAOImp;
import abcweddinghallbooking_ms.Model.Customer;
import java.awt.geom.RoundRectangle2D;
import java.text.MessageFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author sanduni punchihewa
 */
public class ACustomer extends javax.swing.JFrame {

    /**
     * Creates new form ACustomer
     */
    public ACustomer() {
        initComponents();
        Load();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 40, 40));
        curDateTime();
    }

    public void curDateTime(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd    HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        lblDate.setText(dtf.format(now));
    }

    public void Load() {
        CustomerDAOImp dao = new CustomerDAOImp();
        List<Customer> list = dao.list();
        DefaultTableModel dft = (DefaultTableModel) tblCustomer.getModel();
        dft.setRowCount(0);
        for (Customer cs : list) {
            int id = cs.getCustomer_id();
            String name = cs.getName();
            Date date_of_birth = cs.getDate_of_birth();
            int age = cs.getAge();
            String gender = cs.getGender();
            String nic_no = cs.getNic_no();
            String contact_no = cs.getContact_no();
            String email = cs.getEmail();
            String address = cs.getAddress();

            dft.addRow(new Object[]{id, name, date_of_birth, age, gender, nic_no, contact_no, email, address});
        }
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new rojeru_san.complementos.RSTableMetro();
        txtFullName = new rojerusan.RSMetroTextPlaceHolder();
        txtAge = new rojerusan.RSMetroTextPlaceHolder();
        txtNicNo = new rojerusan.RSMetroTextPlaceHolder();
        txtContactNo = new rojerusan.RSMetroTextPlaceHolder();
        txtEmail = new rojerusan.RSMetroTextPlaceHolder();
        txtaddress = new rojerusan.RSMetroTextPlaceHolder();
        DateDateOfBirth = new rojeru_san.componentes.RSDateChooser();
        btnAdd = new rojerusan.RSMaterialButtonRectangle();
        btnUpdate = new rojerusan.RSMaterialButtonRectangle();
        btnDelete = new rojerusan.RSMaterialButtonRectangle();
        txtCustomerID6 = new rojerusan.RSMetroTextPlaceHolder();
        btnPrint = new rojerusan.RSMaterialButtonRectangle();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        rSButtonHover1 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover11 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover10 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover9 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover8 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover6 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover5 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover4 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover3 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover2 = new rojeru_san.complementos.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel5.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel5.setkStartColor(new java.awt.Color(51, 102, 0));
        kGradientPanel5.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menu (1).png"))); // NOI18N
        kGradientPanel5.add(jLabel1);
        jLabel1.setBounds(12, 12, 24, 24);

        jPanel3.setBackground(new java.awt.Color(204, 51, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(2, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        kGradientPanel5.add(jPanel3);
        jPanel3.setBounds(48, 12, 4, 30);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ABC COMPANY - RESOURCE ALLOCATION SYSTEM");
        jLabel4.setAlignmentY(0.0F);
        kGradientPanel5.add(jLabel4);
        jLabel4.setBounds(270, 10, 491, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/luxury.png"))); // NOI18N
        kGradientPanel5.add(jLabel2);
        jLabel2.setBounds(230, 10, 24, 24);

        lblDate.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("2022.05.04   23:34:45");
        kGradientPanel5.add(lblDate);
        lblDate.setBounds(810, 20, 200, 14);

        getContentPane().add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 50));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel15.setText("Full Name  :");
        jPanel14.add(jLabel15);
        jLabel15.setBounds(20, 22, 110, 42);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel17.setText("Date Of Birth :");
        jPanel14.add(jLabel17);
        jLabel17.setBounds(20, 70, 120, 42);

        cmbGender.setEditable(true);
        cmbGender.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cmbGender.setForeground(new java.awt.Color(0, 51, 0));
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel14.add(cmbGender);
        cmbGender.setBounds(155, 173, 231, 42);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel18.setText("Age :");
        jPanel14.add(jLabel18);
        jLabel18.setBounds(20, 124, 56, 42);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel19.setText("Gender :");
        jPanel14.add(jLabel19);
        jLabel19.setBounds(20, 172, 100, 42);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel16.setText("NIC NO:");
        jPanel14.add(jLabel16);
        jLabel16.setBounds(430, 40, 90, 16);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 0));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel20.setText("Contact NO :");
        jPanel14.add(jLabel20);
        jLabel20.setBounds(427, 79, 110, 24);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 0));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel21.setText("Email :");
        jPanel14.add(jLabel21);
        jLabel21.setBounds(427, 129, 65, 24);

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 51, 0));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel22.setText("Adress :");
        jPanel14.add(jLabel22);
        jLabel22.setBounds(427, 182, 75, 24);

        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setBorder(null);
        jPanel14.add(txtID);
        txtID.setBounds(50, 240, 34, 16);

        tblCustomer.setBackground(new java.awt.Color(0, 51, 0));
        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Date Of Birth", "Age", "Gender", "Nic No", "Contact No", "Email", "Address"
            }
        ));
        tblCustomer.setColorBackgoundHead(new java.awt.Color(0, 51, 0));
        tblCustomer.setColorFilasForeground1(new java.awt.Color(0, 102, 0));
        tblCustomer.setColorFilasForeground2(new java.awt.Color(0, 102, 0));
        tblCustomer.setColorSelBackgound(new java.awt.Color(0, 102, 0));
        tblCustomer.setFuenteFilas(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblCustomer.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblCustomer.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        jPanel14.add(jScrollPane1);
        jScrollPane1.setBounds(20, 330, 754, 222);

        txtFullName.setForeground(new java.awt.Color(0, 51, 0));
        txtFullName.setBorderColor(new java.awt.Color(0, 153, 0));
        txtFullName.setBotonColor(new java.awt.Color(0, 51, 0));
        txtFullName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFullNameFocusLost(evt);
            }
        });
        jPanel14.add(txtFullName);
        txtFullName.setBounds(155, 25, 231, 35);

        txtAge.setForeground(new java.awt.Color(0, 51, 0));
        txtAge.setBorderColor(new java.awt.Color(0, 153, 0));
        txtAge.setBotonColor(new java.awt.Color(0, 51, 0));
        txtAge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAgeFocusLost(evt);
            }
        });
        jPanel14.add(txtAge);
        txtAge.setBounds(155, 124, 231, 35);

        txtNicNo.setForeground(new java.awt.Color(0, 51, 0));
        txtNicNo.setBorderColor(new java.awt.Color(0, 153, 0));
        txtNicNo.setBotonColor(new java.awt.Color(0, 51, 0));
        txtNicNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel14.add(txtNicNo);
        txtNicNo.setBounds(540, 30, 227, 35);

        txtContactNo.setForeground(new java.awt.Color(0, 51, 0));
        txtContactNo.setBorderColor(new java.awt.Color(0, 153, 0));
        txtContactNo.setBotonColor(new java.awt.Color(0, 51, 0));
        txtContactNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtContactNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContactNoFocusLost(evt);
            }
        });
        jPanel14.add(txtContactNo);
        txtContactNo.setBounds(539, 73, 227, 35);

        txtEmail.setForeground(new java.awt.Color(0, 51, 0));
        txtEmail.setBorderColor(new java.awt.Color(0, 153, 0));
        txtEmail.setBotonColor(new java.awt.Color(0, 51, 0));
        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel14.add(txtEmail);
        txtEmail.setBounds(539, 123, 227, 35);

        txtaddress.setForeground(new java.awt.Color(0, 51, 0));
        txtaddress.setBorderColor(new java.awt.Color(0, 153, 0));
        txtaddress.setBotonColor(new java.awt.Color(0, 51, 0));
        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel14.add(txtaddress);
        txtaddress.setBounds(539, 176, 227, 35);

        DateDateOfBirth.setBackground(new java.awt.Color(0, 51, 0));
        DateDateOfBirth.setColorBackground(new java.awt.Color(0, 102, 0));
        DateDateOfBirth.setColorButtonHover(new java.awt.Color(0, 255, 51));
        DateDateOfBirth.setColorDiaActual(new java.awt.Color(0, 153, 51));
        DateDateOfBirth.setColorForeground(new java.awt.Color(0, 102, 51));
        DateDateOfBirth.setColorSelForeground(new java.awt.Color(0, 51, 0));
        DateDateOfBirth.setColorTextDiaActual(new java.awt.Color(0, 51, 0));
        DateDateOfBirth.setPlaceholder("Date Of Birth");
        jPanel14.add(DateDateOfBirth);
        DateDateOfBirth.setBounds(155, 76, 231, 36);

        btnAdd.setBackground(new java.awt.Color(0, 102, 102));
        btnAdd.setText("ADD");
        btnAdd.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel14.add(btnAdd);
        btnAdd.setBounds(210, 260, 121, 47);

        btnUpdate.setBackground(new java.awt.Color(0, 102, 51));
        btnUpdate.setText("UPDATE");
        btnUpdate.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel14.add(btnUpdate);
        btnUpdate.setBounds(370, 260, 121, 47);

        btnDelete.setBackground(new java.awt.Color(51, 51, 0));
        btnDelete.setText("DELETE");
        btnDelete.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel14.add(btnDelete);
        btnDelete.setBounds(530, 260, 121, 47);

        txtCustomerID6.setForeground(new java.awt.Color(255, 255, 255));
        txtCustomerID6.setBorderColor(new java.awt.Color(255, 255, 255));
        txtCustomerID6.setBotonColor(new java.awt.Color(0, 51, 0));
        jPanel14.add(txtCustomerID6);
        txtCustomerID6.setBounds(40, 280, 30, 35);

        btnPrint.setBackground(new java.awt.Color(51, 153, 0));
        btnPrint.setText("PRINT TABLE");
        btnPrint.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel14.add(btnPrint);
        btnPrint.setBounds(220, 560, 420, 47);

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 790, 630));

        kGradientPanel7.setkEndColor(new java.awt.Color(0, 204, 51));
        kGradientPanel7.setkStartColor(new java.awt.Color(0, 51, 0));
        kGradientPanel7.setLayout(null);

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel7.add(jPanel15);
        jPanel15.setBounds(0, 0, 50, 40);

        jPanel16.setBackground(new java.awt.Color(0, 0, 0));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel7.add(jPanel16);
        jPanel16.setBounds(0, 50, 50, 40);

        jPanel17.setBackground(new java.awt.Color(0, 0, 0));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/municipal.png"))); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel7.add(jPanel17);
        jPanel17.setBounds(0, 100, 50, 40);

        jPanel18.setBackground(new java.awt.Color(0, 0, 0));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel7.add(jPanel18);
        jPanel18.setBounds(0, 150, 50, 40);

        jPanel19.setBackground(new java.awt.Color(0, 0, 0));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer.png"))); // NOI18N

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel7.add(jPanel19);
        jPanel19.setBounds(0, 200, 50, 40);

        jPanel20.setBackground(new java.awt.Color(0, 0, 0));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/click.png"))); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel7.add(jPanel20);
        jPanel20.setBounds(0, 250, 50, 40);

        jPanel21.setBackground(new java.awt.Color(0, 0, 0));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/document.png"))); // NOI18N

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel7.add(jPanel21);
        jPanel21.setBounds(0, 300, 50, 40);

        jPanel22.setBackground(new java.awt.Color(0, 0, 0));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/online-payment.png"))); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel7.add(jPanel22);
        jPanel22.setBounds(0, 350, 50, 40);

        jPanel23.setBackground(new java.awt.Color(0, 0, 0));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png"))); // NOI18N

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel7.add(jPanel23);
        jPanel23.setBounds(0, 530, 50, 40);

        jPanel24.setBackground(new java.awt.Color(0, 0, 0));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/no.png"))); // NOI18N

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel7.add(jPanel24);
        jPanel24.setBounds(0, 580, 50, 40);

        rSButtonHover1.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover1.setText("Exit");
        rSButtonHover1.setColorHover(java.awt.Color.red);
        rSButtonHover1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        kGradientPanel7.add(rSButtonHover1);
        rSButtonHover1.setBounds(50, 580, 180, 40);

        rSButtonHover11.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover11.setText("LogOut");
        rSButtonHover11.setColorHover(java.awt.Color.orange);
        rSButtonHover11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover11ActionPerformed(evt);
            }
        });
        kGradientPanel7.add(rSButtonHover11);
        rSButtonHover11.setBounds(50, 530, 180, 40);

        rSButtonHover10.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover10.setText("Payment");
        rSButtonHover10.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover10.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover10ActionPerformed(evt);
            }
        });
        kGradientPanel7.add(rSButtonHover10);
        rSButtonHover10.setBounds(50, 350, 180, 40);

        rSButtonHover9.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover9.setText("Cancellation");
        rSButtonHover9.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover9.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover9ActionPerformed(evt);
            }
        });
        kGradientPanel7.add(rSButtonHover9);
        rSButtonHover9.setBounds(50, 300, 180, 40);

        rSButtonHover8.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover8.setText("Booking");
        rSButtonHover8.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover8.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover8ActionPerformed(evt);
            }
        });
        kGradientPanel7.add(rSButtonHover8);
        rSButtonHover8.setBounds(50, 250, 180, 40);

        rSButtonHover6.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonHover6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 255, 0)));
        rSButtonHover6.setText("Customer");
        rSButtonHover6.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonHover6.setColorText(new java.awt.Color(0, 51, 0));
        rSButtonHover6.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover6ActionPerformed(evt);
            }
        });
        kGradientPanel7.add(rSButtonHover6);
        rSButtonHover6.setBounds(50, 200, 180, 40);

        rSButtonHover5.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover5.setText("Search Hall");
        rSButtonHover5.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover5.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover5ActionPerformed(evt);
            }
        });
        kGradientPanel7.add(rSButtonHover5);
        rSButtonHover5.setBounds(50, 150, 180, 40);

        rSButtonHover4.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover4.setText("Hall");
        rSButtonHover4.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover4.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover4ActionPerformed(evt);
            }
        });
        kGradientPanel7.add(rSButtonHover4);
        rSButtonHover4.setBounds(50, 100, 180, 40);

        rSButtonHover3.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover3.setText("Admin");
        rSButtonHover3.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover3.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover3ActionPerformed(evt);
            }
        });
        kGradientPanel7.add(rSButtonHover3);
        rSButtonHover3.setBounds(50, 50, 180, 40);

        rSButtonHover2.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover2.setText("Home");
        rSButtonHover2.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover2.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover2ActionPerformed(evt);
            }
        });
        kGradientPanel7.add(rSButtonHover2);
        rSButtonHover2.setBounds(50, 0, 190, 40);

        getContentPane().add(kGradientPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 230, 630));

        setSize(new java.awt.Dimension(1018, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void rSButtonHover11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover11ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover11ActionPerformed

    private void rSButtonHover10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover10ActionPerformed
        Apayment payment = new Apayment();
        payment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover10ActionPerformed

    private void rSButtonHover9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover9ActionPerformed
        ACancellation cancellation = new ACancellation();
        cancellation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover9ActionPerformed

    private void rSButtonHover8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover8ActionPerformed
        ABookingHall booking = new ABookingHall();
        booking.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover8ActionPerformed

    private void rSButtonHover6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover6ActionPerformed
        ACustomer customer = new ACustomer();
        customer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover6ActionPerformed

    private void rSButtonHover5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover5ActionPerformed
        AsearchHall asearch = new AsearchHall();
        asearch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover5ActionPerformed

    private void rSButtonHover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover4ActionPerformed
        AHall ahall = new AHall();
        ahall.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover4ActionPerformed

    private void rSButtonHover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover3ActionPerformed
        User user = new User();
        user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover3ActionPerformed

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed
        AdminHome ahome = new AdminHome();
        ahome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed


if(txtAge.getText().isEmpty()|| txtContactNo.getText().isEmpty() || txtCustomerID6.getText().isEmpty() || txtEmail.getText().isEmpty() || txtFullName.getText().isEmpty() || txtID.getText().isEmpty() || txtNicNo.getText().isEmpty() || txtaddress.getText().isEmpty() || cmbGender.getSelectedItem().equals(null) || DateDateOfBirth.getDatoFecha().equals(null)){
    JOptionPane.showMessageDialog(this, "Fields are empty");
}        else{
    Customer cs = new Customer();
       // int customer_id = Integer.parseInt(txtID.getText());
        String name = txtFullName.getText();
        Date date_of_birth = DateDateOfBirth.getDatoFecha();
        int age = Integer.parseInt(txtAge.getText());
        String gender = cmbGender.getSelectedItem().toString();
        String nic_no = txtNicNo.getText();
        String contact_no = txtContactNo.getText();
        String email = txtEmail.getText();
        String address = txtaddress.getText();

        cs.setName(name);
        cs.setDate_of_birth(date_of_birth);
        cs.setAge(age);
        cs.setGender(gender);
        cs.setNic_no(nic_no);
        cs.setContact_no(contact_no);
        cs.setEmail(email);
        cs.setAddress(address);
        //cs.setCustomer_id(customer_id);

        CustomerDAOImp dao = new CustomerDAOImp();
        dao.save(cs);
        Load();
        txtFullName.setText("");
        txtAge.setText("");
        txtContactNo.setText("");
        txtEmail.setText("");
        txtNicNo.setText("");
        txtaddress.setText("");
        cmbGender.setSelectedItem("");
}

        

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        

        Customer cs = new Customer();

        int id = Integer.parseInt(txtID.getText());
        String name = txtFullName.getText();
        Date date_of_birth = DateDateOfBirth.getDatoFecha();
        int age = Integer.parseInt(txtAge.getText());
        String gender = cmbGender.getSelectedItem().toString();
        String nic_no = txtNicNo.getText();
        String contact_no = txtContactNo.getText();
        String email = txtEmail.getText();
        String address = txtaddress.getText();

        cs.setCustomer_id(id);
        cs.setName(name);
        cs.setDate_of_birth(date_of_birth);
        cs.setAge(age);
        cs.setGender(gender);
        cs.setNic_no(nic_no);
        cs.setContact_no(contact_no);
        cs.setEmail(email);
        cs.setAddress(address);

        CustomerDAOImp dao = new CustomerDAOImp();
        dao.update(cs);
        Load();
        txtFullName.setText("");
        txtAge.setText("");
        txtContactNo.setText("");
        txtEmail.setText("");
        txtNicNo.setText("");
        txtaddress.setText("");
        cmbGender.setSelectedItem("");

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       Customer cs = new Customer();

        int id = Integer.parseInt(txtID.getText());

        cs.setCustomer_id(id);

        CustomerDAOImp dao = new CustomerDAOImp();
        dao.delete(cs);
        Load();
        txtFullName.setText("");
        txtAge.setText("");
        txtContactNo.setText("");
        txtEmail.setText("");
        txtNicNo.setText("");
        txtaddress.setText("");
        cmbGender.setSelectedItem("");

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        
        int rowNo = tblCustomer.getSelectedRow();
        TableModel model = tblCustomer.getModel();

        txtID.setText(model.getValueAt(rowNo, 0).toString());
        txtFullName.setText(model.getValueAt(rowNo, 1).toString());
        Object dateValue = model.getValueAt(rowNo, 2);
        if (dateValue instanceof Date) {
            Date dateOfBirth = (Date) dateValue;
            DateDateOfBirth.setDatoFecha(dateOfBirth); // Set the selected date
        }
        txtAge.setText(model.getValueAt(rowNo, 3).toString());
        cmbGender.setSelectedItem(model.getValueAt(rowNo, 4).toString());
        txtNicNo.setText(model.getValueAt(rowNo, 5).toString());
        txtContactNo.setText(model.getValueAt(rowNo, 6).toString());
        txtEmail.setText(model.getValueAt(rowNo, 7).toString());
        txtaddress.setText(model.getValueAt(rowNo, 8).toString());
                                            
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
       MessageFormat header = new MessageFormat("Customer Table");
       MessageFormat footer = new MessageFormat("Page(0,number,integer)");
       try{
           tblCustomer.print(JTable.PrintMode.NORMAL,header,footer);
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, e);
       }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
       String emailPattern = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.com$";

Pattern pattern = Pattern.compile(emailPattern);

// Get the input from the email textbox
String email = txtEmail.getText();

// Validate the email against the pattern
Matcher matcher = pattern.matcher(email);
if (matcher.matches()) {
   
} else {
    
    JOptionPane.showMessageDialog(this, "Invalid formation of email.Enter again!");
}
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtContactNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContactNoFocusLost
       // Get the input from the contact textbox
String contact = txtContactNo.getText();

// Define the regex pattern for integers and the plus sign
String contactPattern = "^[0-9+]+$";

// Validate the contact against the pattern
if (contact.matches(contactPattern)) {
    
} else {
   JOptionPane.showMessageDialog(this, "Invalid contact number type.Enter again!");
}

    }//GEN-LAST:event_txtContactNoFocusLost

    private void txtAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAgeFocusLost
       // Get the input from the age textbox
String ageText = txtAge.getText();

// Validate the age input
try {
    int age = Integer.parseInt(ageText);
   
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Invalid Age .Enter again!");
}

    }//GEN-LAST:event_txtAgeFocusLost

    private void txtFullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFullNameFocusLost
       // Get the input from the customer name textbox
String customerName = txtFullName.getText();

// Define the regex pattern for valid names (letters, spaces, and hyphens)
String namePattern = "^[A-Za-z\\s-]+$";

// Validate the customer name against the pattern
if (customerName.matches(namePattern)) {
   
} else {
  JOptionPane.showMessageDialog(this, "Invalid Customer Name .Enter again!");
}

    }//GEN-LAST:event_txtFullNameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ACustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ACustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ACustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ACustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ACustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSDateChooser DateDateOfBirth;
    private rojerusan.RSMaterialButtonRectangle btnAdd;
    private rojerusan.RSMaterialButtonRectangle btnDelete;
    private rojerusan.RSMaterialButtonRectangle btnPrint;
    private rojerusan.RSMaterialButtonRectangle btnUpdate;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel7;
    private javax.swing.JLabel lblDate;
    private rojeru_san.complementos.RSButtonHover rSButtonHover1;
    private rojeru_san.complementos.RSButtonHover rSButtonHover10;
    private rojeru_san.complementos.RSButtonHover rSButtonHover11;
    private rojeru_san.complementos.RSButtonHover rSButtonHover2;
    private rojeru_san.complementos.RSButtonHover rSButtonHover3;
    private rojeru_san.complementos.RSButtonHover rSButtonHover4;
    private rojeru_san.complementos.RSButtonHover rSButtonHover5;
    private rojeru_san.complementos.RSButtonHover rSButtonHover6;
    private rojeru_san.complementos.RSButtonHover rSButtonHover8;
    private rojeru_san.complementos.RSButtonHover rSButtonHover9;
    private rojeru_san.complementos.RSTableMetro tblCustomer;
    private rojerusan.RSMetroTextPlaceHolder txtAge;
    private rojerusan.RSMetroTextPlaceHolder txtContactNo;
    private rojerusan.RSMetroTextPlaceHolder txtCustomerID6;
    private rojerusan.RSMetroTextPlaceHolder txtEmail;
    private rojerusan.RSMetroTextPlaceHolder txtFullName;
    private javax.swing.JTextField txtID;
    private rojerusan.RSMetroTextPlaceHolder txtNicNo;
    private rojerusan.RSMetroTextPlaceHolder txtaddress;
    // End of variables declaration//GEN-END:variables
}
