/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abcweddinghallbooking_ms.View;

import abcweddinghallbooking_ms.Controller.HallDAOImp;
import abcweddinghallbooking_ms.DBConnection;
import abcweddinghallbooking_ms.Model.Hall;
import java.awt.Image;
import java.awt.geom.RoundRectangle2D;
import java.io.ByteArrayInputStream;
import java.sql.Blob;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
/**
 *
 * @author sanduni punchihewa
 */
public class AllHolls extends javax.swing.JFrame {

    /**
     * Creates new form AllHolls
     */
    public AllHolls() {
        initComponents();
        Load();
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),40,40));
        curDateTime();
    }
    
    
    
    public void curDateTime(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd    HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        lblDate.setText(dtf.format(now));
    }
    
    
    public void Load() {
        HallDAOImp dao = new HallDAOImp();
        List<Hall> list = dao.list();
        DefaultTableModel dft = (DefaultTableModel) tblHall.getModel();
        dft.setRowCount(0);
        for (Hall hall : list) {
            int id = hall.getHallID();
            String name = hall.getHallName();
           
            int ppd = hall.getPricePerDay();
            String type = hall.getHallType();
            String availability = hall.getAvailablity();
            Blob photo = hall.getPhoto();
           ;

            dft.addRow(new Object[]{id, name,  type,ppd, availability,  photo});
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtHallID = new rojerusan.RSMetroTextPlaceHolder();
        txtHallName = new rojerusan.RSMetroTextPlaceHolder();
        txtHallType = new rojerusan.RSMetroTextPlaceHolder();
        txtPriceperday = new rojerusan.RSMetroTextPlaceHolder();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHall = new rojeru_san.complementos.RSTableMetro();
        txtAvailability = new rojerusan.RSMetroTextPlaceHolder();
        lblPhoto = new rojerusan.RSLabelImage();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        rSButtonHover4 = new rojeru_san.complementos.RSButtonHover();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rSButtonHover5 = new rojeru_san.complementos.RSButtonHover();
        jPanel20 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rSButtonHover8 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover6 = new rojeru_san.complementos.RSButtonHover();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        rSButtonHover11 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover2 = new rojeru_san.complementos.RSButtonHover();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel5.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel5.setkStartColor(new java.awt.Color(51, 102, 0));
        kGradientPanel5.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menu (1).png"))); // NOI18N
        kGradientPanel5.add(jLabel1);
        jLabel1.setBounds(12, 12, 24, 24);

        jPanel3.setBackground(new java.awt.Color(204, 51, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(2, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        kGradientPanel5.add(jPanel3);
        jPanel3.setBounds(48, 12, 4, 30);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ABC COMPANY - RESOURCE ALLOCATION SYSTEM");
        jLabel4.setAlignmentY(0.0F);
        kGradientPanel5.add(jLabel4);
        jLabel4.setBounds(266, 12, 491, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/luxury.png"))); // NOI18N
        kGradientPanel5.add(jLabel2);
        jLabel2.setBounds(230, 12, 24, 24);

        lblDate.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("2022.05.04   23:34:45");
        kGradientPanel5.add(lblDate);
        lblDate.setBounds(800, 20, 210, 14);

        getContentPane().add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 50));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel15.setText("Hall Name  :");
        jPanel14.add(jLabel15);
        jLabel15.setBounds(30, 360, 94, 24);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel19.setText("photo of Hall  :");
        jPanel14.add(jLabel19);
        jLabel19.setBounds(440, 440, 120, 24);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel17.setText("Hall Type  :");
        jPanel14.add(jLabel17);
        jLabel17.setBounds(30, 430, 100, 24);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel16.setText("Price Per Day  :");
        jPanel14.add(jLabel16);
        jLabel16.setBounds(30, 540, 114, 24);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel18.setText("Availablity  :");
        jPanel14.add(jLabel18);
        jLabel18.setBounds(30, 480, 94, 24);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 0));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel20.setText("Hall ID  :");
        jPanel14.add(jLabel20);
        jLabel20.setBounds(470, 360, 90, 24);

        txtHallID.setForeground(new java.awt.Color(0, 51, 0));
        txtHallID.setBorderColor(new java.awt.Color(0, 102, 0));
        txtHallID.setBotonColor(new java.awt.Color(0, 51, 0));
        jPanel14.add(txtHallID);
        txtHallID.setBounds(560, 360, 190, 35);

        txtHallName.setForeground(new java.awt.Color(0, 51, 0));
        txtHallName.setBorderColor(new java.awt.Color(0, 102, 0));
        txtHallName.setBotonColor(new java.awt.Color(0, 51, 0));
        jPanel14.add(txtHallName);
        txtHallName.setBounds(160, 360, 250, 35);

        txtHallType.setForeground(new java.awt.Color(0, 51, 0));
        txtHallType.setBorderColor(new java.awt.Color(0, 102, 0));
        txtHallType.setBotonColor(new java.awt.Color(0, 51, 0));
        jPanel14.add(txtHallType);
        txtHallType.setBounds(160, 420, 250, 35);

        txtPriceperday.setForeground(new java.awt.Color(0, 51, 0));
        txtPriceperday.setBorderColor(new java.awt.Color(0, 102, 0));
        txtPriceperday.setBotonColor(new java.awt.Color(0, 51, 0));
        jPanel14.add(txtPriceperday);
        txtPriceperday.setBounds(160, 540, 250, 35);

        tblHall.setBackground(new java.awt.Color(0, 51, 0));
        tblHall.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hall ID", "Hall Name", "Hall Type", "Price per Day", "Availability", "Photo"
            }
        ));
        tblHall.setColorBackgoundHead(new java.awt.Color(0, 51, 0));
        tblHall.setColorFilasForeground1(new java.awt.Color(0, 102, 0));
        tblHall.setColorFilasForeground2(new java.awt.Color(0, 102, 0));
        tblHall.setColorSelBackgound(new java.awt.Color(0, 102, 0));
        tblHall.setFuenteFilas(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblHall.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblHall.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblHall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHallMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHall);

        jPanel14.add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 754, 300);

        txtAvailability.setForeground(new java.awt.Color(0, 51, 0));
        txtAvailability.setBorderColor(new java.awt.Color(0, 102, 0));
        txtAvailability.setBotonColor(new java.awt.Color(0, 51, 0));
        txtAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailabilityActionPerformed(evt);
            }
        });
        jPanel14.add(txtAvailability);
        txtAvailability.setBounds(160, 480, 250, 35);

        lblPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 3));
        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/loupe (2).png"))); // NOI18N
        lblPhoto.setToolTipText("Photo of Hotel");
        jPanel14.add(lblPhoto);
        lblPhoto.setBounds(560, 440, 190, 140);

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 790, 630));

        kGradientPanel6.setkEndColor(new java.awt.Color(0, 204, 51));
        kGradientPanel6.setkStartColor(new java.awt.Color(0, 51, 0));
        kGradientPanel6.setLayout(null);

        rSButtonHover4.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonHover4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(51, 255, 0)));
        rSButtonHover4.setText("All Halls");
        rSButtonHover4.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonHover4.setColorText(new java.awt.Color(0, 51, 0));
        rSButtonHover4.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover4ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover4);
        rSButtonHover4.setBounds(50, 50, 180, 40);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/luxury.png"))); // NOI18N
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 0, 38, 40);

        kGradientPanel6.add(jPanel4);
        jPanel4.setBounds(0, 50, 50, 0);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/municipal.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel6);
        jPanel6.setBounds(0, 100, 50, 40);

        rSButtonHover5.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover5.setText("Available Halls");
        rSButtonHover5.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover5.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover5ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover5);
        rSButtonHover5.setBounds(50, 100, 180, 40);

        jPanel20.setBackground(new java.awt.Color(0, 0, 0));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home (2).png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/luxury.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel6.add(jPanel20);
        jPanel20.setBounds(0, 0, 50, 40);

        rSButtonHover8.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover8.setText("Home");
        rSButtonHover8.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover8.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover8ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover8);
        rSButtonHover8.setBounds(50, 0, 180, 40);

        rSButtonHover6.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover6.setText("Payment");
        rSButtonHover6.setColorHover(new java.awt.Color(0, 255, 51));
        rSButtonHover6.setColorTextHover(new java.awt.Color(0, 51, 0));
        rSButtonHover6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover6ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover6);
        rSButtonHover6.setBounds(50, 150, 180, 40);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/online-payment.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel11);
        jPanel11.setBounds(0, 150, 50, 40);

        rSButtonHover11.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover11.setText("LogOut");
        rSButtonHover11.setColorHover(java.awt.Color.orange);
        rSButtonHover11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover11ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover11);
        rSButtonHover11.setBounds(50, 530, 180, 40);

        rSButtonHover2.setBackground(new java.awt.Color(0, 102, 51));
        rSButtonHover2.setText("Exit");
        rSButtonHover2.setColorHover(java.awt.Color.red);
        rSButtonHover2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        rSButtonHover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover2ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(rSButtonHover2);
        rSButtonHover2.setBounds(50, 580, 180, 40);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel12);
        jPanel12.setBounds(0, 530, 50, 40);

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/no.png"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel13);
        jPanel13.setBounds(0, 580, 50, 41);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/luxury.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel6.add(jPanel7);
        jPanel7.setBounds(0, 50, 50, 40);

        getContentPane().add(kGradientPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 230, 630));

        setSize(new java.awt.Dimension(1018, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover4ActionPerformed
        AllHolls allhalls = new AllHolls();
        allhalls.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover4ActionPerformed

    private void rSButtonHover5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover5ActionPerformed
        AvailableHalls availableHalls = new AvailableHalls();
        availableHalls.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover5ActionPerformed

    private void rSButtonHover11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover11ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover11ActionPerformed

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void rSButtonHover8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover8ActionPerformed
        UserHome userHome = new UserHome();
        userHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover8ActionPerformed

    private void tblHallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHallMouseClicked
            int rowNo = tblHall.getSelectedRow();
            TableModel model = tblHall.getModel();
            
            txtHallID.setText(model.getValueAt(rowNo, 0).toString());
            txtHallName.setText(model.getValueAt(rowNo, 1).toString());
            txtHallType.setText(model.getValueAt(rowNo, 2).toString());
            txtPriceperday.setText(model.getValueAt(rowNo, 3).toString());
            txtAvailability.setText(model.getValueAt(rowNo, 4).toString());
            
            try{
                
                Connection con = DBConnection.getConnection();
                PreparedStatement pst = con.prepareStatement("select photo from hall where hall_id = ?");
                pst.setInt(1, Integer.parseInt(model.getValueAt(rowNo, 0).toString()));
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    byte[] imageData = rs.getBytes("photo");
                    Image image = ImageIO.read(new ByteArrayInputStream(imageData));
                    Image scaledImage = image.getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_SMOOTH);
                    lblPhoto.setIcon(new ImageIcon(scaledImage));
                    
                }
                
               
                
            }catch(Exception ex){
                ex.printStackTrace();
            }
    }//GEN-LAST:event_tblHallMouseClicked

    private void rSButtonHover6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover6ActionPerformed
        CardPayment cp = new CardPayment();
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonHover6ActionPerformed

    private void txtAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailabilityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllHolls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllHolls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllHolls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllHolls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllHolls().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private javax.swing.JLabel lblDate;
    private rojerusan.RSLabelImage lblPhoto;
    private rojeru_san.complementos.RSButtonHover rSButtonHover11;
    private rojeru_san.complementos.RSButtonHover rSButtonHover2;
    private rojeru_san.complementos.RSButtonHover rSButtonHover4;
    private rojeru_san.complementos.RSButtonHover rSButtonHover5;
    private rojeru_san.complementos.RSButtonHover rSButtonHover6;
    private rojeru_san.complementos.RSButtonHover rSButtonHover8;
    private rojeru_san.complementos.RSTableMetro tblHall;
    private rojerusan.RSMetroTextPlaceHolder txtAvailability;
    private rojerusan.RSMetroTextPlaceHolder txtHallID;
    private rojerusan.RSMetroTextPlaceHolder txtHallName;
    private rojerusan.RSMetroTextPlaceHolder txtHallType;
    private rojerusan.RSMetroTextPlaceHolder txtPriceperday;
    // End of variables declaration//GEN-END:variables
}
