/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abcweddinghallbooking_ms.View;

import abcweddinghallbooking_ms.Controller.AdminDAOImp;
import abcweddinghallbooking_ms.Controller.RoundBorder;
import abcweddinghallbooking_ms.DBConnection;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;


/**
 *
 * @author sanduni punchihewa
 */
public class LoginAdmin extends javax.swing.JFrame {

    /**
     * Creates new form LoginAdmin
     */
    public LoginAdmin() {
        initComponents();
        lblvisible.setVisible(false);
        
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),40,40));
        
       
    }

    
    
    //verify creds
    public void LoginM(){
         String name = txtUserName.getText();
        String pw =  txtPassword.getText();
        
        
        try{
            Connection con = DBConnection.getConnection();
            
            PreparedStatement pst = con.prepareStatement("select * from admin where username=? and Upassword =?" );
            pst.setString(1,name);
            pst.setString(2, pw);
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "Login succefull");
                AdminHome ahome = new AdminHome();
                ahome.setVisible(true);
                this.dispose();
                        
            }else{
                JOptionPane.showMessageDialog(this, "Invlid user name or password");
            }
            
        }catch(Exception e){
            e.getStackTrace();
        }
    }
    
    
    
    //validtion
    public boolean validateLogin(){
        String name = txtUserName.getText();
        String pw =  txtPassword.getText();
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter userName");
            return false;
        }
        if(pw.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter password");
            return false;
        }
        return true;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtPassword = new rojerusan.RSPasswordTextPlaceHolder();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnLogin = new rojerusan.RSMaterialButtonRectangle();
        txtUserName = new rojerusan.RSMetroTextPlaceHolder();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnSignUp = new rojerusan.RSMaterialButtonRectangle();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblhide = new javax.swing.JLabel();
        lblvisible = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassword.setBackground(new java.awt.Color(204, 255, 255));
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 255, 51)));
        txtPassword.setForeground(new java.awt.Color(0, 51, 0));
        txtPassword.setOpaque(true);
        txtPassword.setPhColor(new java.awt.Color(0, 51, 0));
        txtPassword.setPlaceholder("*Password");
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user (1).png"))); // NOI18N
        jLabel12.setText(" UserName  :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 130, 42));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lock (1).png"))); // NOI18N
        jLabel13.setText(" Password  :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 127, 40));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, 25));

        btnLogin.setBackground(new java.awt.Color(0, 102, 0));
        btnLogin.setText("LOGIN");
        btnLogin.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 121, 47));

        txtUserName.setBackground(new java.awt.Color(204, 255, 255));
        txtUserName.setForeground(new java.awt.Color(0, 51, 0));
        txtUserName.setBorderColor(new java.awt.Color(0, 204, 0));
        txtUserName.setBotonColor(new java.awt.Color(0, 51, 0));
        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUserName.setOpaque(true);
        txtUserName.setPhColor(new java.awt.Color(0, 51, 51));
        txtUserName.setPlaceholder("* User Name");
        jPanel2.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 210, 40));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 255, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSignUp.setBackground(new java.awt.Color(0, 102, 102));
        btnSignUp.setText("SIGNUP");
        btnSignUp.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 47));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Please signUp here.");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("If you haven't an Account");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("WELLCOME BACK !");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN as User.");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 20));

        jPanel2.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 390));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        lblhide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hide.png"))); // NOI18N
        lblhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhideMouseClicked(evt);
            }
        });
        jPanel2.add(lblhide, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        lblvisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/visible.png"))); // NOI18N
        lblvisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblvisibleMouseClicked(evt);
            }
        });
        jPanel2.add(lblvisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(60, 50, 660, 390);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rsz_sunset-pool.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -5, 790, 510);

        setSize(new java.awt.Dimension(780, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(validateLogin()){
           String username = txtUserName.getText();
                String password = new String(txtPassword.getPassword());

                // Create an instance of the controller class
                AdminDAOImp adminDAOImp = new AdminDAOImp();

                // Call the login method in the controller
                boolean loggedIn = adminDAOImp.login(username, password);

                if (loggedIn) {
                    JOptionPane.showMessageDialog(null, "Login Successful!");
                    AdminHome ah = new AdminHome();
                    ah.setVisible(true);
                    this.dispose();
                            
                } else {
                    JOptionPane.showMessageDialog(null, "Login Failed!");
                }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
       SignUp signUp = new SignUp();
       signUp.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void lblvisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvisibleMouseClicked
       txtPassword.setEchoChar('*');
       lblvisible.setVisible(false);
       lblhide.setVisible(true);
        
    }//GEN-LAST:event_lblvisibleMouseClicked

    private void lblhideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhideMouseClicked
        txtPassword.setEchoChar((char)0);
        lblhide.setVisible(false);
        lblvisible.setVisible(true);
    }//GEN-LAST:event_lblhideMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnLogin;
    private rojerusan.RSMaterialButtonRectangle btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblhide;
    private javax.swing.JLabel lblvisible;
    private rojerusan.RSPasswordTextPlaceHolder txtPassword;
    private rojerusan.RSMetroTextPlaceHolder txtUserName;
    // End of variables declaration//GEN-END:variables
}
