/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abcweddinghallbooking_ms.View;

import abcweddinghallbooking_ms.Controller.HallAvailabiltyCheck;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author sanduni punchihewa
 */
public class SearchHallForDates extends javax.swing.JFrame {

    /**
     * Creates new form SearchHallForDates
     */
    public SearchHallForDates() {
        initComponents();
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtHallID = new rojerusan.RSMetroTextPlaceHolder();
        btnAdd = new rojerusan.RSMaterialButtonRectangle();
        jLabel27 = new javax.swing.JLabel();
        dateCheckIn = new rojeru_san.componentes.RSDateChooser();
        jLabel28 = new javax.swing.JLabel();
        DateCheckOut = new rojeru_san.componentes.RSDateChooser();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Hall ID :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 180, 46, 16);

        txtHallID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 2, true));
        txtHallID.setForeground(new java.awt.Color(0, 51, 0));
        txtHallID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtHallID);
        txtHallID.setBounds(150, 170, 206, 42);

        btnAdd.setBackground(new java.awt.Color(0, 102, 102));
        btnAdd.setText("Search");
        btnAdd.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(150, 360, 121, 47);

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel27.setText("Check In :");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(42, 240, 90, 24);

        dateCheckIn.setBackground(new java.awt.Color(0, 51, 0));
        dateCheckIn.setColorBackground(new java.awt.Color(0, 102, 0));
        dateCheckIn.setColorButtonHover(new java.awt.Color(0, 255, 51));
        dateCheckIn.setColorDiaActual(new java.awt.Color(0, 153, 51));
        dateCheckIn.setColorForeground(new java.awt.Color(0, 102, 51));
        dateCheckIn.setColorSelForeground(new java.awt.Color(0, 51, 0));
        dateCheckIn.setColorTextDiaActual(new java.awt.Color(0, 51, 0));
        dateCheckIn.setPlaceholder("Check In Date");
        jPanel1.add(dateCheckIn);
        dateCheckIn.setBounds(150, 230, 240, 40);

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel28.setText("Check Out :");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(31, 300, 100, 24);

        DateCheckOut.setBackground(new java.awt.Color(0, 51, 0));
        DateCheckOut.setColorBackground(new java.awt.Color(0, 102, 0));
        DateCheckOut.setColorButtonHover(new java.awt.Color(0, 255, 51));
        DateCheckOut.setColorDiaActual(new java.awt.Color(0, 153, 51));
        DateCheckOut.setColorForeground(new java.awt.Color(0, 102, 51));
        DateCheckOut.setColorSelForeground(new java.awt.Color(0, 51, 0));
        DateCheckOut.setColorTextDiaActual(new java.awt.Color(0, 51, 0));
        DateCheckOut.setPlaceholder("Check Out Date");
        jPanel1.add(DateCheckOut);
        DateCheckOut.setBounds(150, 290, 240, 40);

        kGradientPanel6.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel6.setkStartColor(new java.awt.Color(51, 102, 0));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ABC COMPANY - RESOURCE ALLOCATION SYSTEM");
        jLabel5.setAlignmentY(0.0F);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/luxury.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addGroup(kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel6Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(kGradientPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(kGradientPanel6);
        kGradientPanel6.setBounds(0, 0, 440, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 438, 509));

        setSize(new java.awt.Dimension(436, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
HallAvailabiltyCheck obj=new  HallAvailabiltyCheck();
        int hallId=Integer.parseInt(txtHallID.getText());
       Date checkin = (Date) dateCheckIn.getDatoFecha();
        Date checkout = (Date) DateCheckOut.getDatoFecha();
        
        LocalDate startDate=LocalDate.ofInstant(checkin.toInstant(),ZoneId.systemDefault());
        LocalDate endDate=LocalDate.ofInstant(checkout.toInstant(), ZoneId.systemDefault());
        
        
        obj.isbooked(hallId,startDate,endDate);

       
    }//GEN-LAST:event_btnAddActionPerformed

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel25MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchHallForDates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchHallForDates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchHallForDates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchHallForDates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchHallForDates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSDateChooser DateCheckOut;
    private rojerusan.RSMaterialButtonRectangle btnAdd;
    private rojeru_san.componentes.RSDateChooser dateCheckIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel6;
    private rojerusan.RSMetroTextPlaceHolder txtHallID;
    // End of variables declaration//GEN-END:variables
}
