/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abcweddinghallbooking_ms.View;
import abcweddinghallbooking_ms.Controller.AdminDAOImp;
import abcweddinghallbooking_ms.DBConnection;
import abcweddinghallbooking_ms.Model.Admin;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author sanduni punchihewa
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        
         generateCaptchaCode();
        captchaLabel.setText(generateCaptchaCode());
        panelVerify.setVisible(false);
        btnRegister.setEnabled(false);
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),40,40));
    }
    
    
     private String generateCaptchaCode() {
        String codeChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        StringBuilder captchaCodeBuilder = new StringBuilder();
        for (int i = 0; i < 6; i++) {
            int randomIndex = (int) (Math.random() * codeChars.length());
            captchaCodeBuilder.append(codeChars.charAt(randomIndex));
        }
        return captchaCodeBuilder.toString();
        
    }
    
     
     
    //check for duplicate users
      public boolean checkDuplicateUser(){
        String name =  txtName.getText();
        boolean isExist = false;
        
        
        try{
            
            
            Connection con = DBConnection.getConnection();
            
            PreparedStatement pst = con.prepareStatement("Select * from admin where name =?");
            pst.setString(1, name);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                isExist = true;
            }
            else{
                isExist=false;
            }
            
        }
        catch(Exception ex){
            ex.getStackTrace();
        }
       return isExist;
    }   
    
      
      //validation //validation
    
    public boolean validateSignUp(){
        
         String name = txtName.getText();
        String address = txtAddress.getText();
        
        String email = txtEmail.getText();
        String telephoneNumber = txtTelephoneNo.getText();
        String username = txtUserName.getText();
        String Password = txtPassword.getText();
        
        int age = Integer.parseInt(txtAge.getText());
        
        String gender = cmbGender.getSelectedItem().toString();
        
        Date dateofBirth = dateofbirth.getDatoFecha();
        Long l1 = dateofBirth.getTime();
        java.sql.Date sdateOfBirth = new java.sql.Date(l1);
        
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter name");
            return false;
        }
        
         if(sdateOfBirth.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter Date of Birth");
            return false;
        }
         
          if(gender.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter gender");
            return false;
        }
           
        
           if(address.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter address");
            return false;
        }
           if(email.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter email");
            return false;
        }
           if(telephoneNumber.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter telephone No");
            return false;
        }
           if(username.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter userName");
            return false;
        }
        if(Password.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter password");
            return false;
        }
         
     return true;
     
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        txtName = new rojerusan.RSMetroTextPlaceHolder();
        txtAge = new rojerusan.RSMetroTextPlaceHolder();
        dateofbirth = new rojeru_san.componentes.RSDateChooser();
        txtAddress = new rojerusan.RSMetroTextPlaceHolder();
        txtEmail = new rojerusan.RSMetroTextPlaceHolder();
        txtTelephoneNo = new rojerusan.RSMetroTextPlaceHolder();
        txtUserName = new rojerusan.RSMetroTextPlaceHolder();
        txtPassword = new rojerusan.RSMetroTextPlaceHolder();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        checkbox = new java.awt.Checkbox();
        btnRegister = new rojerusan.RSMaterialButtonRectangle();
        BTNlOGIN = new rojerusan.RSMaterialButtonRectangle();
        panelVerify = new javax.swing.JPanel();
        captchaLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        captchaTextBox = new javax.swing.JTextField();
        JButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0,200));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SIGNUP");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(20, 20, 770, 70);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,180));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(333, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(377, 59, 0, 2);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel12.setText("Name  :");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 20, 70, 42);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel13.setText("Date OF Birth : ");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(12, 73, 111, 42);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel14.setText("Age   :");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(12, 127, 62, 42);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel15.setText("Address  :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(12, 236, 93, 42);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel16.setText("EMail  :");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 290, 100, 42);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel17.setText("Telephone NO  :");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(12, 346, 130, 42);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel18.setText("UserName :");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(12, 405, 94, 42);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel19.setText("Password  :");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(12, 459, 95, 42);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel21.setText("Gender  :");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 180, 100, 42);

        cmbGender.setEditable(true);
        cmbGender.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cmbGender.setForeground(new java.awt.Color(0, 51, 0));
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female" }));
        jPanel2.add(cmbGender);
        cmbGender.setBounds(140, 180, 232, 42);

        txtName.setForeground(new java.awt.Color(0, 51, 0));
        txtName.setBorderColor(new java.awt.Color(0, 102, 51));
        txtName.setBotonColor(new java.awt.Color(0, 51, 0));
        txtName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtName.setPhColor(new java.awt.Color(0, 51, 51));
        txtName.setPlaceholder("Full Name");
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        jPanel2.add(txtName);
        txtName.setBounds(140, 20, 232, 42);

        txtAge.setForeground(new java.awt.Color(0, 51, 0));
        txtAge.setBorderColor(new java.awt.Color(0, 102, 51));
        txtAge.setBotonColor(new java.awt.Color(0, 51, 0));
        txtAge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAge.setPhColor(new java.awt.Color(0, 51, 51));
        txtAge.setPlaceholder("Age");
        jPanel2.add(txtAge);
        txtAge.setBounds(138, 127, 232, 42);

        dateofbirth.setBackground(new java.awt.Color(0, 51, 0));
        dateofbirth.setColorBackground(new java.awt.Color(0, 102, 0));
        dateofbirth.setColorButtonHover(new java.awt.Color(0, 255, 51));
        dateofbirth.setColorDiaActual(new java.awt.Color(0, 153, 51));
        dateofbirth.setColorForeground(new java.awt.Color(0, 102, 51));
        dateofbirth.setColorSelForeground(new java.awt.Color(0, 51, 0));
        dateofbirth.setColorTextDiaActual(new java.awt.Color(0, 51, 0));
        dateofbirth.setPlaceholder("Date Of Birth");
        jPanel2.add(dateofbirth);
        dateofbirth.setBounds(140, 80, 231, 36);

        txtAddress.setForeground(new java.awt.Color(0, 51, 0));
        txtAddress.setBorderColor(new java.awt.Color(0, 102, 51));
        txtAddress.setBotonColor(new java.awt.Color(0, 51, 0));
        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAddress.setPhColor(new java.awt.Color(0, 51, 51));
        txtAddress.setPlaceholder("Address");
        jPanel2.add(txtAddress);
        txtAddress.setBounds(138, 237, 232, 42);

        txtEmail.setForeground(new java.awt.Color(0, 51, 0));
        txtEmail.setBorderColor(new java.awt.Color(0, 102, 51));
        txtEmail.setBotonColor(new java.awt.Color(0, 51, 0));
        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmail.setPhColor(new java.awt.Color(0, 51, 51));
        txtEmail.setPlaceholder("Email");
        jPanel2.add(txtEmail);
        txtEmail.setBounds(138, 292, 232, 42);

        txtTelephoneNo.setForeground(new java.awt.Color(0, 51, 0));
        txtTelephoneNo.setBorderColor(new java.awt.Color(0, 102, 51));
        txtTelephoneNo.setBotonColor(new java.awt.Color(0, 51, 0));
        txtTelephoneNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTelephoneNo.setPhColor(new java.awt.Color(0, 51, 51));
        txtTelephoneNo.setPlaceholder("TelephoneNo");
        jPanel2.add(txtTelephoneNo);
        txtTelephoneNo.setBounds(138, 351, 232, 42);

        txtUserName.setForeground(new java.awt.Color(0, 51, 0));
        txtUserName.setBorderColor(new java.awt.Color(0, 102, 51));
        txtUserName.setBotonColor(new java.awt.Color(0, 51, 0));
        txtUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUserName.setPhColor(new java.awt.Color(0, 51, 51));
        txtUserName.setPlaceholder("UserName");
        jPanel2.add(txtUserName);
        txtUserName.setBounds(138, 410, 232, 37);

        txtPassword.setForeground(new java.awt.Color(0, 51, 0));
        txtPassword.setBorderColor(new java.awt.Color(0, 102, 51));
        txtPassword.setBotonColor(new java.awt.Color(0, 51, 0));
        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPassword.setPhColor(new java.awt.Color(0, 51, 51));
        txtPassword.setPlaceholder("Password");
        jPanel2.add(txtPassword);
        txtPassword.setBounds(138, 460, 232, 42);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 90, 390, 570);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0,180));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/degree.png"))); // NOI18N
        jLabel20.setText("Terms And Condition :");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 12, -1, -1));

        textArea1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        textArea1.setForeground(new java.awt.Color(0, 51, 0));
        textArea1.setText("1. When you complete your Booking, you accept these Terms and any other terms that you’re provided with during the booking process.\n\n2. If anything in these Terms is (or becomes) invalid or, unenforceable:\n\nit will still be enforced to the fullest extent permitted by law\nyou will still be bound by everything else in the Terms. \nIf there’s any mismatch between general and specific terms, the specific terms will apply.\n3. The English version of these Terms is the original. If there’s any dispute about the Terms, or any mismatch between the Terms in English and in another language, the Terms as they appear in English will apply. (You can change the language at the top of this page.)");
        jPanel4.add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 46, 323, 145));

        checkbox.setBackground(new java.awt.Color(51, 51, 51));
        checkbox.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        checkbox.setForeground(new java.awt.Color(255, 255, 255));
        checkbox.setLabel("Agree With Terms And Condition");
        checkbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkboxMouseClicked(evt);
            }
        });
        jPanel4.add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 201, -1, -1));

        btnRegister.setBackground(new java.awt.Color(0, 102, 102));
        btnRegister.setText("Register");
        btnRegister.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 121, 47));

        BTNlOGIN.setBackground(new java.awt.Color(0, 102, 0));
        BTNlOGIN.setText("LOGIN");
        BTNlOGIN.setActionCommand("Login");
        BTNlOGIN.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        BTNlOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlOGINActionPerformed(evt);
            }
        });
        jPanel4.add(BTNlOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 121, 47));

        panelVerify.setBackground(new java.awt.Color(51, 51, 51));
        panelVerify.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelVerify.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        captchaLabel.setFont(new java.awt.Font("Monospaced", 1, 30)); // NOI18N
        captchaLabel.setText("jLabel3");
        panelVerify.add(captchaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 130, 31));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/R (1).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        panelVerify.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 210, 50));

        captchaTextBox.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        panelVerify.add(captchaTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 230, 35));

        JButton.setBackground(new java.awt.Color(0, 102, 0));
        JButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JButton.setForeground(new java.awt.Color(255, 255, 255));
        JButton.setText("VERIFY");
        JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonActionPerformed(evt);
            }
        });
        panelVerify.add(JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jPanel4.add(panelVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 240, 298, 176));

        getContentPane().add(jPanel4);
        jPanel4.setBounds(420, 90, 370, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-leeloo-thefirst-5038747.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 806, 670);

        setSize(new java.awt.Dimension(805, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void checkboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkboxMouseClicked
        if(checkbox.isEnabled()){
            panelVerify.setVisible(true);
        }
        else{
            panelVerify.setVisible(false);
        }
    }//GEN-LAST:event_checkboxMouseClicked

    private void JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonActionPerformed
        String enteredCode = captchaTextBox.getText().trim();
        String captchaCode = captchaLabel.getText().trim();
        if (enteredCode.equalsIgnoreCase(captchaCode)) {
            JOptionPane.showMessageDialog(this, "Captcha code matched!", "Success", JOptionPane.INFORMATION_MESSAGE);
            btnRegister.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Captcha code not matched!", "Error", JOptionPane.ERROR_MESSAGE);
            captchaLabel.setText(generateCaptchaCode());
            btnRegister.setEnabled(false);
        }
        captchaTextBox.setText("");

    }//GEN-LAST:event_JButtonActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        if(txtAddress.getText().isEmpty() || txtAge.getText().isEmpty() || txtEmail.getText().isEmpty() || txtName.getText().isEmpty() || txtPassword.getText().isEmpty() ||  txtTelephoneNo.getText().isEmpty() || txtUserName.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "Empty Fields");
        }
        
        else{
             Admin adm = new Admin();
       
        String name = txtName.getText();
        Date date_of_birth = dateofbirth.getDatoFecha();
        int age = Integer.parseInt(txtAge.getText());
        String gender = cmbGender.getSelectedItem().toString();
        String address = txtAddress.getText();
        String email= txtEmail.getText();
        String telephoneNo = txtTelephoneNo.getText();
        String username = txtUserName.getText();
        String password = txtPassword.getText();

        adm.setName(name);
        adm.setDateOfBirth(date_of_birth);
        adm.setAge(age);
        adm.setGender(gender);
        adm.setAddress(address);
        adm.setEmail(email);
        adm.setTelephoneNo(telephoneNo);
        adm.setUserName(username);
        adm.setPassword(password);
        

        AdminDAOImp dao = new AdminDAOImp();
        dao.save(adm);
        
        txtName.setText("");
        txtAge.setText("");
        txtTelephoneNo.setText("");
        txtEmail.setText("");
        txtPassword.setText("");
        txtAddress.setText("");
        cmbGender.setSelectedItem("");
        txtUserName.setText("");
        }
       
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void BTNlOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlOGINActionPerformed
        LoginAdmin loga = new LoginAdmin();
        loga.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNlOGINActionPerformed

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
      if(checkDuplicateUser()== true){
            JOptionPane.showInternalMessageDialog(this,"username already exist");
        }
    }//GEN-LAST:event_txtNameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle BTNlOGIN;
    private javax.swing.JButton JButton;
    private rojerusan.RSMaterialButtonRectangle btnRegister;
    private javax.swing.JLabel captchaLabel;
    private javax.swing.JTextField captchaTextBox;
    private java.awt.Checkbox checkbox;
    private javax.swing.JComboBox<String> cmbGender;
    private rojeru_san.componentes.RSDateChooser dateofbirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panelVerify;
    private java.awt.TextArea textArea1;
    private rojerusan.RSMetroTextPlaceHolder txtAddress;
    private rojerusan.RSMetroTextPlaceHolder txtAge;
    private rojerusan.RSMetroTextPlaceHolder txtEmail;
    private rojerusan.RSMetroTextPlaceHolder txtName;
    private rojerusan.RSMetroTextPlaceHolder txtPassword;
    private rojerusan.RSMetroTextPlaceHolder txtTelephoneNo;
    private rojerusan.RSMetroTextPlaceHolder txtUserName;
    // End of variables declaration//GEN-END:variables
}
